language: java
dist: trusty
sudo: false

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer


script: ./gradlew clean build --no-daemon --info --stacktrace

after_success:
  - ./gradlew test jacocoTestReport coveralls --no-daemon