language: java
dist: trusty
sudo: false

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer


script: ./gradlew clean build -x test
#after_success:
#  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report